// Code generated by go-mockgen-tool: https://github.com/jamesrr39/go-mockgen-tool. DO NOT EDIT.

package example

import (
	"io"
	"github.com/jamesrr39/go-mockgen-tool/example/extrapkg"
	"github.com/jamesrr39/go-mockgen-tool/example/extrapkg2"
)

type MockVehicle struct {
	NameFunc         func() string 
	WheelCountFunc   func() (int, error) 
	test2Func        func(mode DriveMode, mode2 DriveMode) func(cargoWeightKg float64) (float64, error) 
	GetReaderFunc    func() io.Reader 
	DoSomethingFunc  func() 
	DoSomething2Func func(err1 extrapkg.Error, err2 extrapkg.Error, a int) extrapkg2.Error2 
	DoSomething3Func func(param0 extrapkg.Error, param1 int, param2 func(a, b string) extrapkg.Error) 
	io.Writer
	SecondInterface
}

func (o *MockVehicle) Name() string {
	if o.NameFunc == nil {
		panic("NameFunc not defined")
	}
	return o.NameFunc()
}

func (o *MockVehicle) WheelCount() (int, error) {
	if o.WheelCountFunc == nil {
		panic("WheelCountFunc not defined")
	}
	return o.WheelCountFunc()
}

func (o *MockVehicle) test2(mode DriveMode, mode2 DriveMode) func(cargoWeightKg float64) (float64, error) {
	if o.test2Func == nil {
		panic("test2Func not defined")
	}
	return o.test2Func(mode, mode2)
}

func (o *MockVehicle) GetReader() io.Reader {
	if o.GetReaderFunc == nil {
		panic("GetReaderFunc not defined")
	}
	return o.GetReaderFunc()
}

func (o *MockVehicle) DoSomething() {
	if o.DoSomethingFunc == nil {
		panic("DoSomethingFunc not defined")
	}
	o.DoSomethingFunc()
}

func (o *MockVehicle) DoSomething2(err1 extrapkg.Error, err2 extrapkg.Error, a int) extrapkg2.Error2 {
	if o.DoSomething2Func == nil {
		panic("DoSomething2Func not defined")
	}
	return o.DoSomething2Func(err1, err2, a)
}

func (o *MockVehicle) DoSomething3(param0 extrapkg.Error, param1 int, param2 func(a, b string) extrapkg.Error) {
	if o.DoSomething3Func == nil {
		panic("DoSomething3Func not defined")
	}
	o.DoSomething3Func(param0, param1, param2)
}
